# Generated by Django 4.2.10 on 2024-03-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_theme_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='Student',
            new_name='student',
        ),
    ]
