# Generated by Django 4.2.10 on 2024-03-05 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_student_theme_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.theme'),
        ),
    ]
